/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const TournamentId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PublicUserProfileView = IDL.Record({
  'freeFireUid' : IDL.Opt(IDL.Text),
  'displayName' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'updatedAt' : Time,
});
export const PublicTournamentDetails = IDL.Record({
  'startTime' : Time,
  'name' : IDL.Text,
  'createdAt' : Time,
  'maxParticipants' : IDL.Opt(IDL.Nat),
  'entryFee' : IDL.Nat,
});
export const PublicUserProfileInput = IDL.Record({
  'freeFireUid' : IDL.Opt(IDL.Text),
  'displayName' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminCreateTournament' : IDL.Func(
      [IDL.Text, IDL.Nat, Time, IDL.Opt(IDL.Nat)],
      [TournamentId],
      [],
    ),
  'adminCreditWallet' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(PublicUserProfileView)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getTournamentDetails' : IDL.Func(
      [TournamentId],
      [PublicTournamentDetails],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PublicUserProfileView)],
      ['query'],
    ),
  'getUserWalletBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinTournament' : IDL.Func([TournamentId], [], []),
  'listTournaments' : IDL.Func(
      [],
      [IDL.Vec(PublicTournamentDetails)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([PublicUserProfileInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const TournamentId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PublicUserProfileView = IDL.Record({
    'freeFireUid' : IDL.Opt(IDL.Text),
    'displayName' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'updatedAt' : Time,
  });
  const PublicTournamentDetails = IDL.Record({
    'startTime' : Time,
    'name' : IDL.Text,
    'createdAt' : Time,
    'maxParticipants' : IDL.Opt(IDL.Nat),
    'entryFee' : IDL.Nat,
  });
  const PublicUserProfileInput = IDL.Record({
    'freeFireUid' : IDL.Opt(IDL.Text),
    'displayName' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminCreateTournament' : IDL.Func(
        [IDL.Text, IDL.Nat, Time, IDL.Opt(IDL.Nat)],
        [TournamentId],
        [],
      ),
    'adminCreditWallet' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(PublicUserProfileView)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getTournamentDetails' : IDL.Func(
        [TournamentId],
        [PublicTournamentDetails],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PublicUserProfileView)],
        ['query'],
      ),
    'getUserWalletBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinTournament' : IDL.Func([TournamentId], [], []),
    'listTournaments' : IDL.Func(
        [],
        [IDL.Vec(PublicTournamentDetails)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([PublicUserProfileInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };