/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PublicTournamentDetails {
  'startTime' : Time,
  'name' : string,
  'createdAt' : Time,
  'maxParticipants' : [] | [bigint],
  'entryFee' : bigint,
}
export interface PublicUserProfileInput {
  'freeFireUid' : [] | [string],
  'displayName' : [] | [string],
}
export interface PublicUserProfileView {
  'freeFireUid' : [] | [string],
  'displayName' : [] | [string],
  'createdAt' : Time,
  'updatedAt' : Time,
}
export type Time = bigint;
export type TournamentId = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminCreateTournament' : ActorMethod<
    [string, bigint, Time, [] | [bigint]],
    TournamentId
  >,
  'adminCreditWallet' : ActorMethod<[Principal, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [PublicUserProfileView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerWalletBalance' : ActorMethod<[], bigint>,
  'getTournamentDetails' : ActorMethod<[TournamentId], PublicTournamentDetails>,
  'getUserProfile' : ActorMethod<[Principal], [] | [PublicUserProfileView]>,
  'getUserWalletBalance' : ActorMethod<[Principal], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinTournament' : ActorMethod<[TournamentId], undefined>,
  'listTournaments' : ActorMethod<[], Array<PublicTournamentDetails>>,
  'saveCallerUserProfile' : ActorMethod<[PublicUserProfileInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];